CREATE TABLE police_stations(
   id   VARCHAR(8) NOT NULL PRIMARY KEY
  ,name VARCHAR(40) NOT NULL
);
INSERT INTO police_stations(id,name) VALUES ('ID000001','JINJA ROAD MAIN STATION');
INSERT INTO police_stations(id,name) VALUES ('ID000002','INTERNAL AFFAIRS POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000003','KITINTALE POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000004','ACHOLI QUARTERS POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000005','KINAWATAKA POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000006','KOLOLO POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000007','MUBS POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000008','KYAMBOGO POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000009','MAWANDA POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000010','KIKAYA POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000011','KISASI POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000012','NTINDA POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000013','KIRA ROAD POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000014','KAMWOKYA POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000015','KYEBANDO POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000016','KIWATULE');
INSERT INTO police_stations(id,name) VALUES ('ID000017','BUKOTO');
INSERT INTO police_stations(id,name) VALUES ('ID000018','BWEYOGERERE POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000019','KIREKA POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000020','KIRINYA POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000021','KIWOLOGOMA POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000022','NAJERA POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000023','NALYA POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000024','NAMUGONGO [POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000025','KIRA CENTRAL POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000026','MUKONO POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000027','SEETA POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000028','MBALALA POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000029','UCU POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000030','NAMAGUNGA POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000031','KATOSI POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000032','KYAMPISI POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000033','NAKIFUMA POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000034','NTUNDA POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000035','NAGALAMA MAIN STN');
INSERT INTO police_stations(id,name) VALUES ('ID000036','STATIONS');
INSERT INTO police_stations(id,name) VALUES ('ID000037','BWAISE POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000038','MAGANJO POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000039','KAWANDA POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000040','LUGOBA POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000041','STATIONS');
INSERT INTO police_stations(id,name) VALUES ('ID000042','STN');
INSERT INTO police_stations(id,name) VALUES ('ID000043','LUGALA POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000044','MAKERERE POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000045','KIKONI POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000046','MULAGO PSTN');
INSERT INTO police_stations(id,name) VALUES ('ID000047','KATWE POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000048','NDEEBA POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000049','NATETE POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000050','SALAMA POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000051','NDEJJE POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000052','MAKINDYE POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000053','MUTUNDWE POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000054','BUNAMWAYA POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000055','KITEBI-KABOWA POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000056','CLOCK TOWER');
INSERT INTO police_stations(id,name) VALUES ('ID000057','KATWE RADIO ROOM');
INSERT INTO police_stations(id,name) VALUES ('ID000058','NSANGI POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000059','MAYA POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000060','NABINGO POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000061','KYENGERA POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000062','NALUMUNYE POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000063','NSANGI SUB COUNTY');
INSERT INTO police_stations(id,name) VALUES ('ID000064','KIBULI POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000065','KISUGU POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000066','GABA POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000067','KABALAGALA MAIN STN');
INSERT INTO police_stations(id,name) VALUES ('ID000068','KANSANGA STN');
INSERT INTO police_stations(id,name) VALUES ('ID000069','STATIONS');
INSERT INTO police_stations(id,name) VALUES ('ID000070','ENTEBBE POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000071','KISUBI POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000072','KASENYI POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000073','KASANJE POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000074','KITOORO POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000075','ABAITABARI POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000076','NAKIWOGO POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000077','MPALA POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000078','KATABI POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000079','NAKAWUKA POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000080','STATIONS');
INSERT INTO police_stations(id,name) VALUES ('ID000081','KAJANSI POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000082','LUBOWA POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000083','BWEBAJA POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000084','AKRITE POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000085','NAMASUBA');
INSERT INTO police_stations(id,name) VALUES ('ID000086','MUTUNGO POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000087','STATIONS');
INSERT INTO police_stations(id,name) VALUES ('ID000088','NKURUMAH POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000089','NAKASERO POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000090','KISEKA POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000091','CPS KAMPALA');
INSERT INTO police_stations(id,name) VALUES ('ID000092','CPS KAPCHORWA');
INSERT INTO police_stations(id,name) VALUES ('ID000093','SIPI POLICE STATION');
INSERT INTO police_stations(id,name) VALUES ('ID000094','CPS KWEEN');
INSERT INTO police_stations(id,name) VALUES ('ID000095','NGENGE PS');
INSERT INTO police_stations(id,name) VALUES ('ID000096','KAPRORON PS');
INSERT INTO police_stations(id,name) VALUES ('ID000097','CPS BUKWO');
INSERT INTO police_stations(id,name) VALUES ('ID000098','SUAM PS');
INSERT INTO police_stations(id,name) VALUES ('ID000099','CHESOWER PS');
INSERT INTO police_stations(id,name) VALUES ('ID000100','CPS');
INSERT INTO police_stations(id,name) VALUES ('ID000101','AWACH');
INSERT INTO police_stations(id,name) VALUES ('ID000102','REGION ASWA');
INSERT INTO police_stations(id,name) VALUES ('ID000103','KITGUM');
INSERT INTO police_stations(id,name) VALUES ('ID000104','CPS- AGAGO');
INSERT INTO police_stations(id,name) VALUES ('ID000105','KALONGO');
INSERT INTO police_stations(id,name) VALUES ('ID000106','CPS');
INSERT INTO police_stations(id,name) VALUES ('ID000107','ATANGA');
INSERT INTO police_stations(id,name) VALUES ('ID000108','PAJULE');
INSERT INTO police_stations(id,name) VALUES ('ID000109','CPS');
INSERT INTO police_stations(id,name) VALUES ('ID000110','MADIOPEI');
INSERT INTO police_stations(id,name) VALUES ('ID000111','PALABEKKAL');
INSERT INTO police_stations(id,name) VALUES ('ID000112','AMURU CPS');
INSERT INTO police_stations(id,name) VALUES ('ID000113','ATIAK');
INSERT INTO police_stations(id,name) VALUES ('ID000114','ELEGU');
INSERT INTO police_stations(id,name) VALUES ('ID000115','CPS');
INSERT INTO police_stations(id,name) VALUES ('ID000116','CPS');
INSERT INTO police_stations(id,name) VALUES ('ID000117','SOROTI CPS');
INSERT INTO police_stations(id,name) VALUES ('ID000118','FIRE & RESCUE – SOROTI');
INSERT INTO police_stations(id,name) VALUES ('ID000119','GWERI');
INSERT INTO police_stations(id,name) VALUES ('ID000120','AMURIA CPS');
INSERT INTO police_stations(id,name) VALUES ('ID000121','393240993');
INSERT INTO police_stations(id,name) VALUES ('ID000122','SERERE CPS');
INSERT INTO police_stations(id,name) VALUES ('ID000123','BUKEDEA CPS');
INSERT INTO police_stations(id,name) VALUES ('ID000124','KACHUMBALA');
INSERT INTO police_stations(id,name) VALUES ('ID000125','KABERAMAIDO CPS');
INSERT INTO police_stations(id,name) VALUES ('ID000126','BULULU');
INSERT INTO police_stations(id,name) VALUES ('ID000127','NGORA CPS');
INSERT INTO police_stations(id,name) VALUES ('ID000128','KOBUKU');
INSERT INTO police_stations(id,name) VALUES ('ID000129','KUMI CPS');
INSERT INTO police_stations(id,name) VALUES ('ID000130','NYERO');
INSERT INTO police_stations(id,name) VALUES ('ID000131','KATAKWI CPS');
INSERT INTO police_stations(id,name) VALUES ('ID000132','KAPELEBYONG CPS');
INSERT INTO police_stations(id,name) VALUES ('ID000133','OBALANGA');
INSERT INTO police_stations(id,name) VALUES ('ID000134','HOIMA MAIN STATION');
INSERT INTO police_stations(id,name) VALUES ('ID000135','KIGOROBYA');
INSERT INTO police_stations(id,name) VALUES ('ID000136','KYANGWALI');
INSERT INTO police_stations(id,name) VALUES ('ID000137','KIZIRANFUMBI');
INSERT INTO police_stations(id,name) VALUES ('ID000138','KIKUUBE CPS');
INSERT INTO police_stations(id,name) VALUES ('ID000139','MASINDI MAIN STATION');
INSERT INTO police_stations(id,name) VALUES ('ID000140','KINYARA');
INSERT INTO police_stations(id,name) VALUES ('ID000141','KAGADI MAIN STATION');
INSERT INTO police_stations(id,name) VALUES ('ID000142','ISUNGA');
INSERT INTO police_stations(id,name) VALUES ('ID000143','MABAALE');
INSERT INTO police_stations(id,name) VALUES ('ID000144','KIBAALE MAIN STATION');
INSERT INTO police_stations(id,name) VALUES ('ID000145','KAKUMIRO MAIN STATION');
INSERT INTO police_stations(id,name) VALUES ('ID000146','IGAYAZA');
INSERT INTO police_stations(id,name) VALUES ('ID000147','KIRYANDONGO MAIN STATION');
INSERT INTO police_stations(id,name) VALUES ('ID000148','BWEYALE');
INSERT INTO police_stations(id,name) VALUES ('ID000149','BULIISA MAIN STATION');
INSERT INTO police_stations(id,name) VALUES ('ID000150','BIISO');
INSERT INTO police_stations(id,name) VALUES ('ID000151','CPS KAMULI');
INSERT INTO police_stations(id,name) VALUES ('ID000152','NAMWENDWA');
INSERT INTO police_stations(id,name) VALUES ('ID000153','MBULAMUTI');
INSERT INTO police_stations(id,name) VALUES ('ID000154','CPS BUYENDE');
INSERT INTO police_stations(id,name) VALUES ('ID000155','KIDERA');
INSERT INTO police_stations(id,name) VALUES ('ID000156','IRUNDU');
INSERT INTO police_stations(id,name) VALUES ('ID000157','JOC');
INSERT INTO police_stations(id,name) VALUES ('ID000158','KALIRO CPS');
INSERT INTO police_stations(id,name) VALUES ('ID000159','DPC');
INSERT INTO police_stations(id,name) VALUES ('ID000160','LUUKA CPS');
INSERT INTO police_stations(id,name) VALUES ('ID000161','RADIO ROOM-MBALE');
INSERT INTO police_stations(id,name) VALUES ('ID000162','CPS COUNTER');
INSERT INTO police_stations(id,name) VALUES ('ID000163','BUSIU P/STN');
INSERT INTO police_stations(id,name) VALUES ('ID000164','NAKALOKE P/STN');
INSERT INTO police_stations(id,name) VALUES ('ID000165','NKOMA P/STN');
INSERT INTO police_stations(id,name) VALUES ('ID000166','NAUYO P/STN');
INSERT INTO police_stations(id,name) VALUES ('ID000167','SIRONKO P/STN');
INSERT INTO police_stations(id,name) VALUES ('ID000168','BUSULANI P/STN');
INSERT INTO police_stations(id,name) VALUES ('ID000169','CPS COUNTER');
INSERT INTO police_stations(id,name) VALUES ('ID000170','CPS-RADIO ROOM');
INSERT INTO police_stations(id,name) VALUES ('ID000171','CPS-RADIO ROOM');
INSERT INTO police_stations(id,name) VALUES ('ID000172','LWAKHAKHA RADIO ROOM');
INSERT INTO police_stations(id,name) VALUES ('ID000173','RPC’S OFFICE');
INSERT INTO police_stations(id,name) VALUES ('ID000174','REG.POLICE-COUNTER');
INSERT INTO police_stations(id,name) VALUES ('ID000175','CPS KABALE');
INSERT INTO police_stations(id,name) VALUES ('ID000176','KATUNA P/STN');
INSERT INTO police_stations(id,name) VALUES ('ID000177','MAZIBA P/STN');
INSERT INTO police_stations(id,name) VALUES ('ID000178','CPS KISORO');
INSERT INTO police_stations(id,name) VALUES ('ID000179','BUNAGANA P/STN');
INSERT INTO police_stations(id,name) VALUES ('ID000180','BAUSANZA BORDER STN');
INSERT INTO police_stations(id,name) VALUES ('ID000181','CPS COUNTER');
INSERT INTO police_stations(id,name) VALUES ('ID000182','RUHINDA P/STN');
INSERT INTO police_stations(id,name) VALUES ('ID000183','RWENSHAMA P/STN');
INSERT INTO police_stations(id,name) VALUES ('ID000184','BUGANGARI P/STN');
INSERT INTO police_stations(id,name) VALUES ('ID000185','KIHIHI P/STN');
INSERT INTO police_stations(id,name) VALUES ('ID000186','ISHASHA P/STN');
INSERT INTO police_stations(id,name) VALUES ('ID000187','KANUNGU P/STN');
INSERT INTO police_stations(id,name) VALUES ('ID000188','RUBANDA P/STN');
INSERT INTO police_stations(id,name) VALUES ('ID000189','BUFUNDI P/STN');
INSERT INTO police_stations(id,name) VALUES ('ID000190','RUKIGA P/STN');
INSERT INTO police_stations(id,name) VALUES ('ID000191','MUHANGA P/STN');
INSERT INTO police_stations(id,name) VALUES ('ID000192','BUKINDA P/STN');
INSERT INTO police_stations(id,name) VALUES ('ID000193','JOC SAVANNAH');
INSERT INTO police_stations(id,name) VALUES ('ID000194','COUNTER CPS');
INSERT INTO police_stations(id,name) VALUES ('ID000195','KASANA P/STN');
INSERT INTO police_stations(id,name) VALUES ('ID000196','WOBULENZI P/STN');
INSERT INTO police_stations(id,name) VALUES ('ID000197','ZIROBWE P/STN');
INSERT INTO police_stations(id,name) VALUES ('ID000198','BOMBO P/STN');
INSERT INTO police_stations(id,name) VALUES ('ID000199','CPS COUNTER');
INSERT INTO police_stations(id,name) VALUES ('ID000200','KAKOOGE P/STN');
INSERT INTO police_stations(id,name) VALUES ('ID000201','MIGYEERA P/STN');
INSERT INTO police_stations(id,name) VALUES ('ID000202','RWAMPANGA P/STN');
INSERT INTO police_stations(id,name) VALUES ('ID000203','KAZWAMA P/STN');
INSERT INTO police_stations(id,name) VALUES ('ID000204','KIWOKO CPS');
INSERT INTO police_stations(id,name) VALUES ('ID000205','NGOMA P/STN');
INSERT INTO police_stations(id,name) VALUES ('ID000206','KAPEKA P/STN');
INSERT INTO police_stations(id,name) VALUES ('ID000207','SEMUTO P/STN');
INSERT INTO police_stations(id,name) VALUES ('ID000208','BUTALANGO P/STN');
INSERT INTO police_stations(id,name) VALUES ('ID000209','NAMUNGALWE P/STN');
INSERT INTO police_stations(id,name) VALUES ('ID000210','BULIDA POLICE STATION');
INSERT INTO police_stations(id,name) VALUES ('ID000211','KALUUBA POLICE STATION');
INSERT INTO police_stations(id,name) VALUES ('ID000212','LOLWE POLICE STATION.');
INSERT INTO police_stations(id,name) VALUES ('ID000213','BWONDA PSTN');
INSERT INTO police_stations(id,name) VALUES ('ID000214','CPS MASAKA');
INSERT INTO police_stations(id,name) VALUES ('ID000215','NYENDO');
INSERT INTO police_stations(id,name) VALUES ('ID000216','KYABAKUZA');
INSERT INTO police_stations(id,name) VALUES ('ID000217','MPUGWE');
INSERT INTO police_stations(id,name) VALUES ('ID000218','CPS');
INSERT INTO police_stations(id,name) VALUES ('ID000219','CPS');
INSERT INTO police_stations(id,name) VALUES ('ID000220','MBIRIZI');
INSERT INTO police_stations(id,name) VALUES ('ID000221','KYAZANGA');
INSERT INTO police_stations(id,name) VALUES ('ID000222','KINONI');
INSERT INTO police_stations(id,name) VALUES ('ID000223','CPS');
INSERT INTO police_stations(id,name) VALUES ('ID000224','CPS');
INSERT INTO police_stations(id,name) VALUES ('ID000225','KASENSERO');
INSERT INTO police_stations(id,name) VALUES ('ID000226','CPS');
INSERT INTO police_stations(id,name) VALUES ('ID000227','CPS');
INSERT INTO police_stations(id,name) VALUES ('ID000228','LUKAYA');
INSERT INTO police_stations(id,name) VALUES ('ID000229','KYAMULIBWA');
INSERT INTO police_stations(id,name) VALUES ('ID000230','BUKULULA');
INSERT INTO police_stations(id,name) VALUES ('ID000231','KALIRO');
INSERT INTO police_stations(id,name) VALUES ('ID000232','LWABEENGE');
INSERT INTO police_stations(id,name) VALUES ('ID000233','CPS');
INSERT INTO police_stations(id,name) VALUES ('ID000234','MATEETE');
INSERT INTO police_stations(id,name) VALUES ('ID000235','LWEMIYAGA');
INSERT INTO police_stations(id,name) VALUES ('ID000236','CPS');
INSERT INTO police_stations(id,name) VALUES ('ID000237','BUTENGA');
INSERT INTO police_stations(id,name) VALUES ('ID000238','MISANVU');
INSERT INTO police_stations(id,name) VALUES ('ID000239','KIKUUTA');
INSERT INTO police_stations(id,name) VALUES ('ID000240','BIGASA');
INSERT INTO police_stations(id,name) VALUES ('ID000241','CPS');
INSERT INTO police_stations(id,name) VALUES ('ID000242','MITYANA BAR (KUNYWA)');
INSERT INTO police_stations(id,name) VALUES ('ID000243','CPS');
INSERT INTO police_stations(id,name) VALUES ('ID000244','CPS');
INSERT INTO police_stations(id,name) VALUES ('ID000245','CPS');
INSERT INTO police_stations(id,name) VALUES ('ID000246','CPS');
INSERT INTO police_stations(id,name) VALUES ('ID000247','CPS');
INSERT INTO police_stations(id,name) VALUES ('ID000248','KAMENGO');
INSERT INTO police_stations(id,name) VALUES ('ID000249','KIBIBI');
INSERT INTO police_stations(id,name) VALUES ('ID000250','MADDU');
INSERT INTO police_stations(id,name) VALUES ('ID000251','JINJA CPS');
INSERT INTO police_stations(id,name) VALUES ('ID000252','NALUFENYA POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000253','WALUKUBA POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000254','BUGEMBE POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000255','BUWENGE POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000256','KAKIRA POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000257','JOC');
INSERT INTO police_stations(id,name) VALUES ('ID000258','MOYO');
INSERT INTO police_stations(id,name) VALUES ('ID000259','OBONGI');
INSERT INTO police_stations(id,name) VALUES ('ID000260','MOYO SUB COUNTY');
INSERT INTO police_stations(id,name) VALUES ('ID000261','ADJUMANI');
INSERT INTO police_stations(id,name) VALUES ('ID000262','DZAIPI');
INSERT INTO police_stations(id,name) VALUES ('ID000263','OFUA');
INSERT INTO police_stations(id,name) VALUES ('ID000264','YUMBE');
INSERT INTO police_stations(id,name) VALUES ('ID000265','LODONGA');
INSERT INTO police_stations(id,name) VALUES ('ID000266','ADIBO');
INSERT INTO police_stations(id,name) VALUES ('ID000267','RADIO ROOM YUMBE');
INSERT INTO police_stations(id,name) VALUES ('ID000268','PTS IKAFE(RADIO ROOM)');
INSERT INTO police_stations(id,name) VALUES ('ID000269','MALABA');
INSERT INTO police_stations(id,name) VALUES ('ID000270','BUSIA CPS');
INSERT INTO police_stations(id,name) VALUES ('ID000271','MASAFU');
INSERT INTO police_stations(id,name) VALUES ('ID000272','BUSOLWE');
INSERT INTO police_stations(id,name) VALUES ('ID000273','PALLISA CPS');
INSERT INTO police_stations(id,name) VALUES ('ID000274','BUDAKA CPS');
INSERT INTO police_stations(id,name) VALUES ('ID000275','KIBUKU CPS');
INSERT INTO police_stations(id,name) VALUES ('ID000276','BUTEBO CPS');
INSERT INTO police_stations(id,name) VALUES ('ID000277','CPS ARUA');
INSERT INTO police_stations(id,name) VALUES ('ID000278','LIA POLICE STATION');
INSERT INTO police_stations(id,name) VALUES ('ID000279','VURRA STATION');
INSERT INTO police_stations(id,name) VALUES ('ID000280','RHINOCAMP POLICE STATION');
INSERT INTO police_stations(id,name) VALUES ('ID000281','OMUGO POLICE STATION');
INSERT INTO police_stations(id,name) VALUES ('ID000282','KOBOKO POLICE STATION');
INSERT INTO police_stations(id,name) VALUES ('ID000283','ORABA POLICE STATION');
INSERT INTO police_stations(id,name) VALUES ('ID000284','BUSIA POLICE STATION');
INSERT INTO police_stations(id,name) VALUES ('ID000285','MARACHA POLICE STATION');
INSERT INTO police_stations(id,name) VALUES ('ID000286','NEBBI POLICE STATION');
INSERT INTO police_stations(id,name) VALUES ('ID000287','GOLI POLICE STATION');
INSERT INTO police_stations(id,name) VALUES ('ID000288','PAIDHA POLICE STATION');
INSERT INTO police_stations(id,name) VALUES ('ID000289','ZOMBO POLICE STATION');
INSERT INTO police_stations(id,name) VALUES ('ID000290','ZEU POLICE STATION');
INSERT INTO police_stations(id,name) VALUES ('ID000291','WARR POLICE STATION');
INSERT INTO police_stations(id,name) VALUES ('ID000292','PAKWACH POLICE STATION');
INSERT INTO police_stations(id,name) VALUES ('ID000293','PANYIMUR POLICE STATION');
INSERT INTO police_stations(id,name) VALUES ('ID000294','LUGAZI');
INSERT INTO police_stations(id,name) VALUES ('ID000295','BUIKWE');
INSERT INTO police_stations(id,name) VALUES ('ID000296','KIYINDI');
INSERT INTO police_stations(id,name) VALUES ('ID000297','MABIRA');
INSERT INTO police_stations(id,name) VALUES ('ID000298','NGOGWE');
INSERT INTO police_stations(id,name) VALUES ('ID000299','KAYUNGA POLICE STATION');
INSERT INTO police_stations(id,name) VALUES ('ID000300','BUSAANA');
INSERT INTO police_stations(id,name) VALUES ('ID000301','GALILAYA');
INSERT INTO police_stations(id,name) VALUES ('ID000302','BUVUMA POLICE STATION');
INSERT INTO police_stations(id,name) VALUES ('ID000303','NJERU POLICE STATION');
INSERT INTO police_stations(id,name) VALUES ('ID000304','BUSHENYI');
INSERT INTO police_stations(id,name) VALUES ('ID000305','RUBIRIZI');
INSERT INTO police_stations(id,name) VALUES ('ID000306','MITOOMA');
INSERT INTO police_stations(id,name) VALUES ('ID000307','SHEEMA');
INSERT INTO police_stations(id,name) VALUES ('ID000308','BUHWEJU');
INSERT INTO police_stations(id,name) VALUES ('ID000309','RCO OFFICE');
INSERT INTO police_stations(id,name) VALUES ('ID000310','CPS KOTIDO');
INSERT INTO police_stations(id,name) VALUES ('ID000311','ABIM CPS');
INSERT INTO police_stations(id,name) VALUES ('ID000312','CPS KAABONG');
INSERT INTO police_stations(id,name) VALUES ('ID000313','KABAROLE MAIN POLICE STATION');
INSERT INTO police_stations(id,name) VALUES ('ID000314','BUNDIBUJO MAIN STATION 754887386 WORKING');
INSERT INTO police_stations(id,name) VALUES ('ID000315','NYAHUKA POLICE STATION 750143815 WORKING');
INSERT INTO police_stations(id,name) VALUES ('ID000316','BUKONJO');
INSERT INTO police_stations(id,name) VALUES ('ID000317','KYARUSHOZI');
INSERT INTO police_stations(id,name) VALUES ('ID000318','BUNYANGABO MAIN STN');
INSERT INTO police_stations(id,name) VALUES ('ID000319','RWIMI P/STN');
INSERT INTO police_stations(id,name) VALUES ('ID000320','RUBONA');
INSERT INTO police_stations(id,name) VALUES ('ID000321','MBARARA CPS');
INSERT INTO police_stations(id,name) VALUES ('ID000322','NTUNGAMO CPS');
INSERT INTO police_stations(id,name) VALUES ('ID000323','KIRUHURA CPS');
INSERT INTO police_stations(id,name) VALUES ('ID000324','IBANDA CPS');
INSERT INTO police_stations(id,name) VALUES ('ID000325','ISINGIRO CPS');
INSERT INTO police_stations(id,name) VALUES ('ID000326','LIRA CPS');
INSERT INTO police_stations(id,name) VALUES ('ID000327','OJWINA');
INSERT INTO police_stations(id,name) VALUES ('ID000328','BUS PARK');
INSERT INTO police_stations(id,name) VALUES ('ID000329','AKOKORO');
INSERT INTO police_stations(id,name) VALUES ('ID000330','APAC');
INSERT INTO police_stations(id,name) VALUES ('ID000331','IBUJE');
INSERT INTO police_stations(id,name) VALUES ('ID000332','NAMBYESO');
INSERT INTO police_stations(id,name) VALUES ('ID000333','KWANIA');
INSERT INTO police_stations(id,name) VALUES ('ID000334','CAWENTE');
INSERT INTO police_stations(id,name) VALUES ('ID000335','ABONGOMOLA');
INSERT INTO police_stations(id,name) VALUES ('ID000336','ALEBTONG');
INSERT INTO police_stations(id,name) VALUES ('ID000337','AKURA');
INSERT INTO police_stations(id,name) VALUES ('ID000338','APALA');
INSERT INTO police_stations(id,name) VALUES ('ID000339','OMORO');
INSERT INTO police_stations(id,name) VALUES ('ID000340','AKALO');
INSERT INTO police_stations(id,name) VALUES ('ID000341','BAALA');
INSERT INTO police_stations(id,name) VALUES ('ID000342','ABOKE');
INSERT INTO police_stations(id,name) VALUES ('ID000343','LORO');
INSERT INTO police_stations(id,name) VALUES ('ID000344','KAMDINI');
INSERT INTO police_stations(id,name) VALUES ('ID000345','MINAKULU');
INSERT INTO police_stations(id,name) VALUES ('ID000346','NAMASALE');
INSERT INTO police_stations(id,name) VALUES ('ID000347','AGOGA');
INSERT INTO police_stations(id,name) VALUES ('ID000348','AMOLATAR');
INSERT INTO police_stations(id,name) VALUES ('ID000349','DOKOLO');
INSERT INTO police_stations(id,name) VALUES ('ID000350','AGWATA');
INSERT INTO police_stations(id,name) VALUES ('ID000351','OTUKE');
INSERT INTO police_stations(id,name) VALUES ('ID000352','OKWANG');
INSERT INTO police_stations(id,name) VALUES ('ID000353','OLILIM');
INSERT INTO police_stations(id,name) VALUES ('ID000354','PYAPAK P/STN');
INSERT INTO police_stations(id,name) VALUES ('ID000355','NABILATUK');
INSERT INTO police_stations(id,name) VALUES ('ID000356','MOROTO BUSPARK');
INSERT INTO police_stations(id,name) VALUES ('ID000357','MOROTO P/STN');
INSERT INTO police_stations(id,name) VALUES ('ID000358','NAKAPIRIPIRIT');
INSERT INTO police_stations(id,name) VALUES ('ID000359','NAKUMATT POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000360','KYAMBOGO LOWER POLICE.POST');
INSERT INTO police_stations(id,name) VALUES ('ID000361','BANDA POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000362','BUGOLOBI BANGALO POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000363','NAGURU DRIVE POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000364','MUTUNGO POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000365','INDUSTRIAL AREA');
INSERT INTO police_stations(id,name) VALUES ('ID000366','NAKAWA POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000367','GOLF COURSE POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000368','JOMAYI POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000369','MAWANDA POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000370','TUBA POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000371','KISASI POLICE STN');
INSERT INTO police_stations(id,name) VALUES ('ID000372','KYANJA POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000373','BUKASA POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000374','MBALWA POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000375','KIGANDA POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000376','NAKISUNGA POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000377','NTAWO POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000378','KISOGA POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000379','SONDE POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000380','NANTABULIRWA POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000381','NAMANVE POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000382','KOOME POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000383','MUKONO TAXI PARK POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000384','NAMATABA POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000385','NTENJERU POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000386','WANTONI POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000387','NAGOJJE POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000388','KIMENYEDE POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000389','NABAALE POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000390','NKONGE POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000391','MAYANGA YANGA POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000392','KALAGI POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000393','KABIMBIRI POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000394','SEETA NAMUGANGA POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000395','POSTS');
INSERT INTO police_stations(id,name) VALUES ('ID000396','NAMERE POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000397','KAKUNGULU POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000398','TUULA POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000399','POSTS');
INSERT INTO police_stations(id,name) VALUES ('ID000400','NAKULE POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000401','LUBIGI POLICE POSTS');
INSERT INTO police_stations(id,name) VALUES ('ID000402','KABULENGWA POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000403','WAMALA POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000404','GOBERO POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000405','RWEMENDE POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000406','BUKALANGO POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000407','KAKONGE POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000408','POSTS');
INSERT INTO police_stations(id,name) VALUES ('ID000409','WORKING TAXI PARK POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000410','MUSAJA ALUMBA POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000411','MUZAANA PLOICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000412','LUBAGA CATHEDRAL POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000413','RIVERSIDE POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000414','MASANAFU POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000415','KASUBI POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000416','NAMUNGOONA POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000417','WAKALIGA POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000418','NAMIREMBE CATHEDRAL PLOICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000419','LAKESIDE POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000420','KISENYI POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000421','NAMIREMBE ROAD POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000422','BAKULI POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000423','KABANYORO POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000424','SEKANYONYI POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000425','KIWENDA POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000426','CANAN ESTATES POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000427','KIJABIJO POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000428','MAIRYE POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000429','GALAMBA POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000430','JAGGALA POLICE OPOPST');
INSERT INTO police_stations(id,name) VALUES ('ID000431','NAMAYINA POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000432','MASSOLI POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000433','LUKWANGA POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000434','NALUVULE POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000435','SSENGE POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000436','KISIMBIRI POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000437','KIMWANYI POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000438','KUBIRI POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000439','WANDEGEYA MARKET POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000440','BUGEMA POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000441','KAVULE POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000442','LDC POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000443','MULAGO CASUALITY POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000444','KIBE POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000445','GADDAFI R/D P/P');
INSERT INTO police_stations(id,name) VALUES ('ID000446','KIBIRI POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000447','NABISAALU POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000448','KIKUMBI POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000449','KIRIMANYANGA POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000450','BUSEGA R/ABOUT P/P');
INSERT INTO police_stations(id,name) VALUES ('ID000451','KIBUMBIRO P/P');
INSERT INTO police_stations(id,name) VALUES ('ID000452','MADALA P/P');
INSERT INTO police_stations(id,name) VALUES ('ID000453','NATETE TAXI PARK P/P');
INSERT INTO police_stations(id,name) VALUES ('ID000454','KABAWO P/P');
INSERT INTO police_stations(id,name) VALUES ('ID000455','KIKAJO P/P');
INSERT INTO police_stations(id,name) VALUES ('ID000456','KABOWA');
INSERT INTO police_stations(id,name) VALUES ('ID000457','KAGUGUBE P/P');
INSERT INTO police_stations(id,name) VALUES ('ID000458','BUDO JUNIOR P/P');
INSERT INTO police_stations(id,name) VALUES ('ID000459','BUDO KINGS P/P');
INSERT INTO police_stations(id,name) VALUES ('ID000460','KAZINGA P/P');
INSERT INTO police_stations(id,name) VALUES ('ID000461','NABAZIZA P/P');
INSERT INTO police_stations(id,name) VALUES ('ID000462','NKOKONJERU P/P');
INSERT INTO police_stations(id,name) VALUES ('ID000463','KABOJA P/P');
INSERT INTO police_stations(id,name) VALUES ('ID000464','KIKAJO P/P');
INSERT INTO police_stations(id,name) VALUES ('ID000465','KATALE P/P');
INSERT INTO police_stations(id,name) VALUES ('ID000466','KASENGE P/P');
INSERT INTO police_stations(id,name) VALUES ('ID000467','KASAWEP/P');
INSERT INTO police_stations(id,name) VALUES ('ID000468','KOONGE P/P');
INSERT INTO police_stations(id,name) VALUES ('ID000469','NSAMBYA P/P');
INSERT INTO police_stations(id,name) VALUES ('ID000470','NABUTITI P/P');
INSERT INTO police_stations(id,name) VALUES ('ID000471','BUZIGA P/P');
INSERT INTO police_stations(id,name) VALUES ('ID000472','BUKASA -ROUND P/P');
INSERT INTO police_stations(id,name) VALUES ('ID000473','MUNYONYO');
INSERT INTO police_stations(id,name) VALUES ('ID000474','POSTS');
INSERT INTO police_stations(id,name) VALUES ('ID000475','BUSSI P/P');
INSERT INTO police_stations(id,name) VALUES ('ID000476','GERENGE P/P');
INSERT INTO police_stations(id,name) VALUES ('ID000477','WAMALA POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000478','HINDU TEMPLE POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000479','KABALE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000480','LUGONJO P/P');
INSERT INTO police_stations(id,name) VALUES ('ID000481','POSTS');
INSERT INTO police_stations(id,name) VALUES ('ID000482','NGOBE POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000483','LUMULI POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000484','KIGO ROAD POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000485','POSTS');
INSERT INTO police_stations(id,name) VALUES ('ID000486','PUNJANI P/P');
INSERT INTO police_stations(id,name) VALUES ('ID000487','COLVILLE P/P');
INSERT INTO police_stations(id,name) VALUES ('ID000488','BIWOLOGOMA P/P');
INSERT INTO police_stations(id,name) VALUES ('ID000489','OLD TAXI PARK P/P');
INSERT INTO police_stations(id,name) VALUES ('ID000490','WILSON ROAD P/P');
INSERT INTO police_stations(id,name) VALUES ('ID000491','WILLIAM STREET P/P');
INSERT INTO police_stations(id,name) VALUES ('ID000492','ARUA PARK P/P');
INSERT INTO police_stations(id,name) VALUES ('ID000493','EM PLAZA P/P');
INSERT INTO police_stations(id,name) VALUES ('ID000494','WORKING TAXI PARK');
INSERT INTO police_stations(id,name) VALUES ('ID000495','KIKUUBO P/P');
INSERT INTO police_stations(id,name) VALUES ('ID000496','RCO OFFICE');
INSERT INTO police_stations(id,name) VALUES ('ID000497','LAYIBI');
INSERT INTO police_stations(id,name) VALUES ('ID000498','LACOR');
INSERT INTO police_stations(id,name) VALUES ('ID000499','GULU UNIVERSITY');
INSERT INTO police_stations(id,name) VALUES ('ID000500','PANDWONG');
INSERT INTO police_stations(id,name) VALUES ('ID000501','PAGER P/P');
INSERT INTO police_stations(id,name) VALUES ('ID000502','PARABONGO');
INSERT INTO police_stations(id,name) VALUES ('ID000503','WALIGO BORDER');
INSERT INTO police_stations(id,name) VALUES ('ID000504','NGOM OROMO');
INSERT INTO police_stations(id,name) VALUES ('ID000505','APIRITI BORDER');
INSERT INTO police_stations(id,name) VALUES ('ID000506','BIBIA');
INSERT INTO police_stations(id,name) VALUES ('ID000507','AKURU KWER');
INSERT INTO police_stations(id,name) VALUES ('ID000508','PABBO');
INSERT INTO police_stations(id,name) VALUES ('ID000509','ANAKA HOSPITAL');
INSERT INTO police_stations(id,name) VALUES ('ID000510','OPIT');
INSERT INTO police_stations(id,name) VALUES ('ID000511','BROOKS CORNER');
INSERT INTO police_stations(id,name) VALUES ('ID000512','BUWALASI P/POST');
INSERT INTO police_stations(id,name) VALUES ('ID000513','BUTEZA P/POST');
INSERT INTO police_stations(id,name) VALUES ('ID000514','BUWAGOGO P/POST');
INSERT INTO police_stations(id,name) VALUES ('ID000515','KATUUGO P/POST');
INSERT INTO police_stations(id,name) VALUES ('ID000516','KAFU FFU DETACH');
INSERT INTO police_stations(id,name) VALUES ('ID000517','BULYAMUSENY P/POST(PRESIDENTIAL FARM)');
INSERT INTO police_stations(id,name) VALUES ('ID000518','SSANJE');
INSERT INTO police_stations(id,name) VALUES ('ID000519','BULO');
INSERT INTO police_stations(id,name) VALUES ('ID000520','KYABADAAZA');
INSERT INTO police_stations(id,name) VALUES ('ID000521','KIRIRI');
INSERT INTO police_stations(id,name) VALUES ('ID000522','KISOZI DETACH');
INSERT INTO police_stations(id,name) VALUES ('ID000523','PALORINYA BASE CAMP');
INSERT INTO police_stations(id,name) VALUES ('ID000524','MASSA');
INSERT INTO police_stations(id,name) VALUES ('ID000525','ELEGU');
INSERT INTO police_stations(id,name) VALUES ('ID000526','BIDIBIDI CAMP');
INSERT INTO police_stations(id,name) VALUES ('ID000527','MULANDA');
INSERT INTO police_stations(id,name) VALUES ('ID000528','LYAMA');
INSERT INTO police_stations(id,name) VALUES ('ID000529','MALABA POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000530','YIVU POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000531','PAROMBO POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000532','KALWANG POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000533','NYARAVUR POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000534','DEI POLICE POST');
INSERT INTO police_stations(id,name) VALUES ('ID000535','WADELAI POLICE POST');
